### ISSUE TITLE
VulkanInit: detect valid memory types for textures and only allocate textures from those types

### ISSUE THREAD

**Issue by azonenberg** [glscopeclient/scopehal#690]
Texture loading is failing on some systems because of using the default card local memory type.

**Comment by bvernoux** [comment]
This issue relates to https://github.com/glscopeclient/scopehal-apps/issues/498

**Comment by azonenberg** [comment]
Looks to be fixed now.

**Comment by bvernoux** [comment]
Issue fixed with https://github.com/glscopeclient/scopehal-apps/commit/4c3ba38d7660e1ff598f42c8dbff7a11c9ac12e3
