### ISSUE TITLE
Bug in USBTMC transport: `else` missing

### ISSUE THREAD

**Issue by CodingMarco** [glscopeclient/scopehal#754]
See: https://github.com/glscopeclient/scopehal/blob/e3fb92510a07f40565ba507046d728cdad0deb22/scopehal/SCPITMCTransport.cpp#L198-L207

the `else` seems to be missing, thus the read() is executed twice which lets the whole thing fail.

**Comment by azonenberg** [comment]
I don't have one of the buggy Siglent firmwares handy to know if this is a bug or if it's a workaround for #652.

@mandl can you have a look?

**Comment by mandl** [comment]
Hello Andrew, he ist right. The else is Missing. Please merge the pull
requests. Thanks for reporting.

Andrew Zonenberg ***@***.***> schrieb am So., 12. März 2023,
12:05:
