### ISSUE TITLE
Issue to build the actual code with MSYS2 / MINGW64 related to usleep (Impact file RSRTO6Oscilloscope.cpp)

### ISSUE THREAD

**Issue by bvernoux** [glscopeclient/scopehal#765]
Issue to build the actual code with MSYS2 / MINGW64 related to usleep (Impact file RSRTO6Oscilloscope.cpp from PR https://github.com/glscopeclient/scopehal/pull/759 )
See https://github.com/glscopeclient/scopehal/search?q=usleep&type=code
Solution is to apply https://github.com/glscopeclient/scopehal/issues/262#issuecomment-696993778

**Comment by azonenberg** [comment]
Fixed in 66719f3f521406fdcc04cb37042483833edb7b5d
