### ISSUE TITLE
Digilent Discovery3 fails on msys2

### ISSUE THREAD

**Issue by ledvinap** [glscopeclient/scopehal#800]
On windows (including msys2 mingw64), `sizeof(int)==sizeof(long)==4`. 
`stol` will then overflow when parsing periods larger than 2us (< 500Kkz).
https://github.com/glscopeclient/scopehal/blob/master/scopehal/DigilentOscilloscope.cpp#L456C10-L456C10

Replacing `stol` with `stoll` fixes windows build, but is a bit of overkill on normal systems (128 bits)

**Comment by bvernoux** [comment]
Yes just replace it with std::stoll() it returns a 64bits (long long) on any 64bits computer and not 128bits
You can push a PR for that

**Comment by ledvinap** [comment]
#802
